### PR TITLE
Update README.md example of trigger for new workflow

### LINKED ISSUE #96: Put in README.md example of trigger for new workflow
"or make comment in PR:"
`Github, generate report for SummaryJavadoc/Example1`

From https://github.com/checkstyle/test-configs/blob/1e98f67239a38c969893ef095b5026a4ad42a6d2/SummaryJavadoc/Example1/README.md

Should be added when we have new workflow.

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #96

### CODE REVIEW

**Comment by romani** [comment]
Make completely new section to do new comment.

Old way should stay as alternate if user doesn't want to do short cut trigger.

**Comment by romani** [comment]
Send PR for single Readme to agree on formatting and wording.

**Comment by romani** [comment]
look at https://github.com/checkstyle/test-configs/pull/130/files for how it should be, not tstrict requirements, but something like this.
to show approach for new workflow above a instructions for old workflow.

**Comment by relentless-pursuit** [comment]
closing as new PR up

**Pull request closed without merging**
