### PR TITLE
Generation of Readme.md

### LINKED ISSUE #91: Generation of Readme.md
We need to generate readme.md to each ExampleX folder to let people easily copy both lines with links and paste to PR.

Readme might be beneficial from the beginning of generation, we can generate whole content of two lines like:
```
Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/list-of-projects.properties
```

So user will just copy paste it, and will not have any issues with it.

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #91

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@romani rather than having a readme.md inside every folder, we can have a master readme which has links for all the examples# including all in one configs.

**Comment by romani** [comment]
Please rebase, to remove first commit.

I updated issue to point on description/discussion thread on how final result should looks like.

We need readme in each folder, nobody knows what Example3 means for some check. Users will walk inside each folder to find config with properties he affected. As he found config, same folder should show ready to copy and paste content , GitHub does hint image over code block to do it in single click.

**Comment by relentless-pursuit** [comment]
> Please rebase, to remove first commit.
> 
> I updated issue to point on description/discussion thread on how final result should looks like.
> 
> We need readme in each folder, nobody knows what Example3 means for some check. Users will walk inside each folder to find config with properties he affected. As he found config, same folder should show ready to copy and paste content , GitHub does hint image over code block to do it in single click.

done

**Comment by romani** [comment]
Title is ok.

Under title text should be like I provided at https://github.com/checkstyle/test-configs/blob/1e98f67239a38c969893ef095b5026a4ad42a6d2/SummaryJavadoc/Example1/README.md
But without "or make comment in PR:", it will be wording for new workflow.

**Comment by relentless-pursuit** [comment]
> Github, generate report
```

# Example1 Example

Configuration file: `https://github.com/checkstyle/test-configs/blob/main/SummaryJavadocCheck/Example1/config.xml`

List of projects using this configuration: `https://github.com/checkstyle/test-configs/blob/main/SummaryJavadocCheck/Example1/list-of-projects.properties`

paste this block to PR description to use such test configs and make comment in PR 'Github, generate report'
```

Something like this?

**Comment by romani** [comment]
No.
Pay attention to border of code block at https://github.com/checkstyle/test-configs/blob/1e98f67239a38c969893ef095b5026a4ad42a6d2/SummaryJavadoc/Example1/README.md?plain=1

All content that user needs is inside code block

**Review by romani — APPROVED** [review]

**Pull request merged**
