### PR TITLE
Part 4: Place list-of-projects.properties in build/resource/main

### LINKED ISSUE #1: Create a script what parses xdocs with example config specified
Create a script that parses the xdocs with example config specifed 

first Check - https://checkstyle.org/checks/naming/abbreviationaswordinname.html#AbbreviationAsWordInName

generated configs should be part of commit together with script (groovy).
or we can start java app from the begining if that is easier.

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Part of #1

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@Romani, since I am new to gradle, i had do a bit of research on this. And, it suggested copyResources task. However, if just rely on the gradle file, it still does the job i.e. copy the properties to` build/resource/main`. But, i guess adding copyResources will give some surity and consistency.

**Comment by relentless-pursuit** [comment]
Screenshot 2024-06-12 at 11 45 11 PM

**Comment by romani** [comment]
It should be part of java logic , not a Gradle.
Such file should be placed in each folder this extractor generates.

**Review by romani — CHANGES_REQUESTED** [review]
Please postpone this PR until we start generating content for git remosi repository folders at root.
No need to test our ability to copy file.

**Comment by romani** [comment]
Time to resume activities in this PR.

**Comment by relentless-pursuit** [comment]
Closing this PR. Redoing changes in https://github.com/checkstyle/test-configs/pull/46

**Pull request closed without merging**
