### PR TITLE
Creating test-configs for block package

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Part of #52

### CODE REVIEW

**Comment by romani** [comment]
Just apply this git diff to commit.

**Comment by relentless-pursuit** [comment]
> Just apply this git diff to commit. New version of all-in-one is good, so diff is good as files are better.

I did in local. But, why is the order changed as per CI? because, i don't see any diff with the ones being shownn in the CI. 
image

**Comment by romani** [comment]
If order is changed, please to ordering in code by `id`  kind of same as you did with properties

**Comment by relentless-pursuit** [comment]
> If order is changed, please to ordering in code by `id` kind of same as you did with properties .
> 
> Hash based collections do not guarantee order.

So, i mean the all-in-one prop is same wrt content. but, the one mentioned that is example1, example2 ordering is changed. but, to my knowledge the regression against which all-in-one.config would be tested remains the same i.e. covering all the eamples.

**Comment by romani** [comment]
Please rephrase, I don't understand you.

**Comment by relentless-pursuit** [comment]
```
diff --git a/EmptyBlock/all-examples-in-one/config-all-in-one.xml b/EmptyBlock/all-examples-in-one/config-all-in-one.xml
index 095321f..0a40b3c 100644
--- a/EmptyBlock/all-examples-in-one/config-all-in-one.xml
+++ b/EmptyBlock/all-examples-in-one/config-all-in-one.xml
@@ -20,17 +20,17 @@
     <module name="TreeWalker">
         <module name="EmptyBlock">
             <property name="id" value="example1"/>
-            <property name="option" value="text"/>
-            <property name="tokens" value="LITERAL_TRY"/>
+            <property name="tokens" value="LITERAL_DEFAULT"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example2"/>
-            <property name="tokens" value="LITERAL_DEFAULT"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example3"/>
+            <property name="option" value="text"/>
+            <property name="tokens" value="LITERAL_TRY"/>
         </module>
```

Original content in local and in lates push:

```
     <module name="TreeWalker">
         <module name="EmptyBlock">
             <property name="id" value="example1"/>
             <property name="option" value="text"/>
             <property name="tokens" value="LITERAL_TRY"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example2"/>
             <property name="tokens" value="LITERAL_DEFAULT"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example3"/>
         </module>
```

Content expected
```
     <module name="TreeWalker">
         <module name="EmptyBlock">
             <property name="id" value="example1"/>
             <property name="tokens" value="LITERAL_DEFAULT"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example2"/>
         </module>
 
         <module name="EmptyBlock">
             <property name="id" value="example3"/>
             <property name="option" value="text"/>
             <property name="tokens" value="LITERAL_TRY"/>
         </module>
```

This happned after I made code changes for ensuring only one argument for package and thereby generating the files. Is the change because of code changes in how i am right now generating the files?

**Comment by relentless-pursuit** [comment]
@romani issue is resolved. i realised that before wiritng to the files, i was not loading them in an order. however, the git diff got me confused as it was not hinting me to do ordering but giving an order very different. you can see now my expected content is even not same as content expected attached above from git diff.

**Review by romani — APPROVED** [review]

**Pull request merged**
