### PR TITLE
Adding all-examples-in-one into Annotation package

### LINKED ISSUE #50: Add examples-all-in-one configs for Annotation package
It adds remaining examples-all-in-one configs for Annotation package

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #50

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Direction is good, please fix CI

**Comment by relentless-pursuit** [comment]
Is the failure in CI relevant?

```
Error walking through the input directory or processing files.
    java.nio.file.NoSuchFileException: .ci-temp/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname
```

**Comment by romani** [comment]
path most likely should be started with `../` as extractor is level down from root of repo

**Comment by relentless-pursuit** [comment]
> path most likely should be started with `../` as extractor is level down from root of repo

I am curious on why it is working in my local.

**Comment by relentless-pursuit** [comment]
> path most likely should be started with `../` as extractor is level down from root of repo

should i change the CI?

**Comment by romani** [comment]
no, run 
https://github.com/checkstyle/test-configs/blob/f9ded631e45aa160fc388877a201ee7964b901c5/.github/workflows/ci.yml#L23
on your local to reproduce

**Comment by romani** [comment]
fix is:
```
✔ ~/java/github/checkstyle/test-configs/extractor [relentless-pursuit/allInOneAnnotation L|✚ 1] 
07:08 $ git diff
diff --git a/extractor/src/main/java/com/example/extractor/Main.java b/extractor/src/main/java/com/example/extractor/Main.java
index ad9135c..85c9409 100644
--- a/extractor/src/main/java/com/example/extractor/Main.java
+++ b/extractor/src/main/java/com/example/extractor/Main.java
@@ -25,7 +25,7 @@ public class Main {
         System.out.println("Using output directory name: " + outputDirName);
 
         // Path to Checkstyle repo
-        String checkstyleRepoPath = ".ci-temp/checkstyle";
+        String checkstyleRepoPath = "../.ci-temp/checkstyle";
 
         // Input directory
         String inputDirectory = checkstyleRepoPath + "/" + pathInRepo;

```

**Comment by relentless-pursuit** [comment]
> no, run
> 
> https://github.com/checkstyle/test-configs/blob/f9ded631e45aa160fc388877a201ee7964b901c5/.github/workflows/ci.yml#L23
> 
> 
> on your local to reproduce

image
i did but succeeding. .but, i guess the fix provided by you should work. waiting for ci.

**Comment by relentless-pursuit** [comment]
@romani CI passing now.

**Review by romani — APPROVED** [review]

**Pull request merged**
