### PR TITLE
Remove hacks with ConfigSerializer 

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Part of #1

### CODE REVIEW

**Comment by romani** [comment]
code is merged on local

**Comment by relentless-pursuit** [comment]
> code is merged on local

i mean i can't fetch these changes? despite trying to fetch, i couldn't see these changes being reflected.

**Comment by relentless-pursuit** [comment]
> code is merged on local

i mean i can't fetch these changes? despite trying to fetch, i couldn't see these changes being reflected.

**Comment by romani** [comment]
Please create one more PR if I missed something

**Comment by relentless-pursuit** [comment]
Okay, i will push the changes of this file along with my PR6.

**Pull request closed without merging**
