### PR TITLE
Use openjdk21 in projects lists

### LINKED ISSUE #124: Use openjdk21 in projects lists
https://github.com/checkstyle/contribution/pull/878 is merged.

Let's update both our files with projects to use openjdk21

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #124

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@romani is the CI failure because of two commits?

**Comment by romani** [comment]
Please update both files that have projects.

**Comment by relentless-pursuit** [comment]
> Please update both files that have projects.

https://github.com/checkstyle/test-configs/pull/125/commits/8a489f66d5b16287d48f09cc664ac9e89ca93a25

I have used 2 commits as you suggested earlier. Am i missing any other file?

**Comment by romani** [comment]
Fix reference https://github.com/relentless-pursuit/test-configs/blob/91ccd57513c298c304d57d6e8fdf0edca976d41a/extractor/src/main/resources/projects-for-example.yml#L6

And update code to throw exception if referenced project is not found

**Comment by relentless-pursuit** [comment]
> Fix reference https://github.com/relentless-pursuit/test-configs/blob/91ccd57513c298c304d57d6e8fdf0edca976d41a/extractor/src/main/resources/projects-for-example.yml#L6
> 
> And update code to throw exception if referenced project is not found

done

**Pull request merged**
