### PR TITLE
Copy new projects to project.properties list from contrib…

### LINKED ISSUE #164: Copy  new projects to project.properties list from contribution repo
Related to https://github.com/checkstyle/contribution/pull/895#issuecomment-2305913445

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Resolves #164

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@Romani please review

**Comment by romani** [comment]
CI is red

**Comment by romani** [comment]
Functional commit has no new projects

**Comment by relentless-pursuit** [comment]
> Functional commit has no new projects

yes, i will put it for blocker. this is a good scenario to create a new workflow which can commit and push changes. currently, working on my repo as a we have some git diff

**Comment by relentless-pursuit** [comment]
> Functional commit has no new projects

my bad. the changes we had in the https://github.com/checkstyle/contribution/pull/895#issuecomment-2305913445 were just openjdk21 right?

**Comment by relentless-pursuit** [comment]
```
Hartshorn|git|https://github.com/Dockbox-OSS/Hartshorn|develop/0.7.0||
camunda|git|https://github.com/camunda/camunda|main||
```

You are talking about this?

**Comment by romani** [comment]
Yes, only this 2 should be copied

**Pull request closed without merging**
